models:
 "gpt-4-turbo":
   api_type: "openai"
   base_url: "https://api.openai.com/v1"
   api_key: ""
   temperature: 0
 "gpt-3.5-turbo":  
   api_type: "openai"  
   base_url: "https://api.openai.com/v1"
   api_key: ""
   temperature: 0
CALC_USAGE: True 
