models:
  "gpt-4-turbo":
    api_type: "openai"
    base_url: "https://api.openai.com/v1"
    api_key: ""
    temperature: 0
  "gpt-3.5-turbo":  
    api_type: "openai"  
    base_url: "https://api.openai.com/v1"
    api_key: ""
    temperature: 0
CALC_USAGE: True 

data_path: "/home/batmanosama/poc-kagnar/experiments/dslmodel-prefect/MetaGPT-MathAI/examples/aflow/data/hotpotqa_test.jsonl"
initial_params:
  creativity: 0.7
  historical_accuracy: 0.8
  narrative_coherence: 0.6
llm_config:
  model: "gpt-4-turbo"
  api_type: "openai"
  base_url: "https://api.openai.com/v1"
  api_key: ""
  temperature: 0
  max_budget: .40
max_iterations: 45
convergence_threshold: 0.01